name: iOS Publish
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
jobs:
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
#    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    uses: .github/workflows/KMMBridge-custom.yml
    with:
      jvmVersion: 17
      versionBaseProperty: LIBRARY_VERSION
#    secrets:
#      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}
